Patch Update: 1.2.3
* Fixed the following error due to case sensitivity during import:

src/data/fieldDefinitions.ts:1:33 - error TS2307: Cannot find module '../models/FieldDefinition' or its corresponding type declarations.

* Replaced jasmine with jest